apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-speech-daemon
  namespace: speech-nandy-io
  labels:
    app: node-speech-daemon
spec:
  selector:
    matchLabels:
      app: node-speech-daemon
  template:
    metadata:
      labels:
        app: node-speech-daemon
    spec:
      nodeSelector:
        audio: enabled
      containers:
      - name: node-speech-daemon
        image: docker.io/nandyio/node-speech-daemon:0.1
        imagePullPolicy: Always
        env:
          - name: K8S_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: REDIS_HOST
            value: db.redis-klot-io
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_CHANNEL
            value: nandy.io/speech
          - name: SPEECH_FILE
            value: /tmp/speech.mp3
          - name: SLEEP
            value: "1"
        securityContext:
          privileged: true
